### ISSUE TITLE
To-do:

### ISSUE THREAD

**Issue by pbarban** [pbarban/MastersThesis-CIRED-CNAM#2]
**Mémoire:**

- [ ] Create online platform with all Rmarkdown
- [ ] Write the thesis

**Article mortality (négaWatt and ADEME):**

- [ ] Projection de pop fec basse
- [ ] Faire une documentation
- [ ] Calculate benefits with new mortality rates
- [ ] Refaire le package HEAT
- [ ] Ponderer la distri Danoise
- [ ] Write codes to measure life expectancy 
- [ ] Run codes on standard deviation to get the confidence interval of all results
- [ ] Meeting with Aurélien (Fin Juillet)
- [ ] Present results to Audrey 

**Project for Eco-Counter:**

- [x] Codes to collect bike data
- [ ] Create an index
- [ ] Add EGT data 
- [ ] Get results 
- [ ] Formatting a presentation
